
reverse_language:
	${PYTHON3} ${LARA}/Code/Python/lara_run.py make_language_reversed_version ${LARA}/Content/antigone/corpus/local_config.json
	${PYTHON3} ${LARA}/Code/Python/lara_run.py treetagger ${LARA}/Content/antigone_en/corpus/local_config.json
	cp ${LARA}/Content/antigone_en/corpus/Tagged_Antigone_en.docx ${LARA}/Content/antigone_en/corpus/TaggedAndCleaned_Antigone_en.docx

